services:
- name: container-nginx
  image: nginx:1.15.4
  capabilities:
  - CAP_AUDIT_WRITE
  - CAP_NET_RAW
  - CAP_DAC_OVERRIDE
  - CAP_NET_BIND_SERVICE
  - CAP_SETUID
  - CAP_CHOWN
  - CAP_FSETID
  - CAP_SETFCAP
  - CAP_SETPCAP
  - CAP_MKNOD
  - CAP_FOWNER
  - CAP_KILL
  - CAP_SETGID
  - CAP_SYS_CHROOT
  binds:
  - /etc/resolv.conf:/etc/resolv.conf
