kernel:
  image: linuxkit/kernel:4.19.8
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
- linuxkit/init:c563953a2277eb73a89d89f70e4b6dcdcfebc2d1
- linuxkit/runc:83d0edb4552b1a5df1f0976f05f442829eac38fe
- linuxkit/containerd:326b096cd5fbab0f864e52721d036cade67599d6
- linuxkit/ca-certificates:v0.6
onboot:
- name: sysctl
  image: linuxkit/sysctl:v0.6
- name: format
  image: linuxkit/format:v0.6
- name: mount
  image: linuxkit/mount:v0.6
  command: ["/usr/bin/mountie", "/var/lib"]
- name: dhcpcd
  image: linuxkit/dhcpcd:v0.6
  command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
- name: metadata
  image: linuxkit/metadata:v0.6
services:
- name: acpid
  image: linuxkit/acpid:v0.6
- name: rngd
  image: linuxkit/rngd:v0.6
- name: dhcpcd
  image: linuxkit/dhcpcd:v0.6
- name: ntpd
  image: linuxkit/openntpd:v0.6
- name: getty
  image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
  env:
  - INSECURE=true
trust:
  org:
  - linuxkit
